myList = [1, 2, 3, 4]
myList.remove(4)
print(myList)
myList.insert(3, 4)
print(myList)
myList.pop(3)
print(myList)
myList.insert(3, 4)
print(myList)
print('\n')

myList.remove(1)
print(myList)
myList.insert(0, 1)
print(myList)
myList.pop(0)
print(myList)
myList.insert(0, 1)
print(myList)
print('\n')

myList.insert(4, 5)
print(myList)
print('\n')

myList[0] = 2
print(myList)
myList.remove(5)
print(myList)
myList.insert(2, 3)
print(myList)
print('\n')
